[package]
name = "apilator"
version = "0.9.4"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
reqwest = { version = "0.12", features = ["json", "gzip", "deflate", "brotli", "multipart"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
dirs = "5"
sysinfo = "0.30"
base64 = "0.23.1"
hmac = "0.12"
sha2 = "0.10"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"

[target.'cfg(windows)'.dependencies]
keyring = { version = "3", features = ["windows-native"] }
winreg = "0.56.0"
windows-sys = { version = "0.60", features = ["Win32_Foundation", "Win32_Security_Cryptography"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
